### ISSUE TITLE
Dagger 2: Require `@Inject` constructor for provision? 

### ISSUE THREAD

**Issue by cgruber** [square/dagger#412]
In Google's Dagger 2.x candidate we have a deviation from the normal assumptions about `@Inject` signals that we think will really clean things up, and we wanted to shop it to the main project, since it's the only substantial departure to Dagger 1.x semantics with respect to client code (that is, to non-configuration, non-module code).  Namely, that for `Bar` to depend on `Foo`, `Foo` has to have an `@Inject` constructor in all cases, even if it uses members-injection.

### context

One piece of context for this question is that in our 2.0 candidate, we've separated the notion of a provision binding from members-injection.  Provision bindings (`@Inject` constructor or `@Provides` method) result in a `Provider<T>` being bound to the key, but members-injection (`@Inject` on a field or method) results in a `MembersInjector<T>` being bound.  A class may have both a `Provider<T>` and a `MembersInjector<T>` if it is both instantiable by Dagger but also needs field/method injection.  In that case, the `Provider<T>` concrete type depends on the `MembersInjector<T>`.

Because of this, it is vastly simpler, clearer, and lines up the developer's expectation of the generated code with the client code.

### where it matters

The sticking point is the current Dagger behavior where a class can be both members-injectable and providable if it has an `@Inject` field, but a default or accessible no-args constructor, like so:

```java
class Foo {
  @Inject Bar bar;
}
```

The above can be depended upon, where in Dagger 2, we are proposing that it could not - it would be suitable for members injection but not provision.  To have it be provided (to dependents) it would have to add an `@Inject` constructor like so:

```java
class Foo {
  @Inject Bar bar;
  @Inject Foo() {}
}
```

### practicalities

For things like Activities, this is fine, since we won't be making `Provider<? extends Activity>` ever, since they can never be instantiated by Dagger anyway.  They are injectable, and they will have a `MembersInjector<T>` created for them.  But it adds a small amount of boilerplate to classes that were using field injection for convenience, readability, or possibly functional reasons, but didn't add a no-args `@Inject constructor`.  In Dagger 2, we propose that they must, and that we never generate a `Provider<T>` (and therefore they will be invalid as a target for a dependency) unless they do so.

Non-dagger-constructable types can always, as now, be provided via `@Provides` methods, so this change is quite aside from that.

### conclusion

We think this is a net improvement, conceptually, aligning the signals with the semantics a little more.  It also cleans up the implementation of the generators and analyzers.

**Comment by relgames** [comment]
Hi @gk5885, you mention ```@Inject``` specification http://docs.oracle.com/javaee/6/api/javax/inject/Inject.html

And it clearly says:
```@Inject is optional for public, no-argument constructors when no other constructors are present. This enables injectors to invoke default constructors.```

I think you are mixing 2 different actions together:
1) Make class providable (a candidate for instantiation), and
2) Actually instantiate a class, injecting it's dependencies: constructor (if exists), then fields, then methods.

```@Inject``` annotation defines dependencies for a constructor, field or method. It makes little sense to use it for non-argument constructor (because there are no dependencies to be injected), and that's why the specification says it is optional.

**Comment by gk5885** [comment]
@relgames, no one disputes that an injector may use public, default constructors.  But, as is the case in Guice when you invoke [`Binder.requireAtInjectOnConstructors()`](http://google.github.io/guice/api-docs/4.0/javadoc/com/google/inject/Binder.html#requireAtInjectOnConstructors--), it is valid for an injector to choose not to.  Much the same way that `@Inject` "may apply to static as well as instance members," that behavior isn't necessarily supported -- that particular bit is actually a called out specifically as a parameter in the tck.  Basically, we're interpreting that bit of the specification to mean that the behavior is _enabled_, but not mandated.

That said, much of the work that we've done with Dagger 2 has eliminated many of the surprises and pitfalls that we were used to seeing with reflectively built graphs, so I would be open to reexamining the tradeoffs between safety and brevity in this case.  I suspect that there will always be some number of restrictions on what we allow to be injected because the full universe of injectable types per the specification includes `String`, `Properties`, `Thread`, etc., for which the default constructor is never the correct thing.  But, a discussion about whether or not this particular tradeoff in the general is still warranted would be worth raising an issue there.

**Comment by relgames** [comment]
@gk5885 I think I see your point. 

I was little bit confused by using ```@Inject``` for allowing other classes to inject a class. I came from a Spring world where multiple annotations exist: ```@Bean``` for explicitly instantiated classes (IMO it's the same as ```@Provides```), ```@Autowired``` (```@Inject```) and ```@Service``` for declaring a bean valid for instantiation and DI. 

So in Dagger, ```@Inject``` is used where in Spring I'd use separate ```@Autowired``` and ```@Service```.
