### ISSUE TITLE
@named annotation with condition

### ISSUE THREAD

**Issue by alorma** [square/dagger#540]
I get a use case where i needed two different interfaces to be provided with the same name, depending on API version (android)

```
@provides
@CustomScope
@Named("NotificationsJobManager")
AppJobManager getAlarmManagerJobManager() {...}

@provides
@CustomScope
@Named("NotificationsJobManager")
AppJobManager getJobSchedulerJobManager() {...}
```

JobScheduler appears on Android Lollipop, so it will be great to have something like:

```
@provides
@CustomScope
@Named("NotificationsJobManager")
AppJobManager getAlarmManagerJobManager() {...}

@provides
@CustomScope
@Named("NotificationsJobManager")
@Condition(Build.Version.SDK_CODE == 21)
AppJobManager getJobSchedulerJobManager() {...}
```
This will work like this:

* If more than one `@provides` are annotated with same `@named` it will not compile
* If those `@named` have a `@condition` annotation:
   * @condition annotated fields: only provide this ones if meet condition
   * method without annotation: use by default

**Comment by JakeWharton** [comment]
Move the condition inside the method and alter the return value based on it. Alternatively, you can apply different modules based on the API level. Both of these are vastly more powerful since you can actually use runtime state in your conditionals (something that is required for your non-working example).
